### ISSUE TITLE
still being maintained?

### ISSUE THREAD

**Issue by sittingbool** [lukechilds/keyv-mongo#35]
is there someone taking care of those pull requests?

**Comment by macrozone** [comment]
@lukechilds there are some security issues with this package because of the mongodb package that is used.

The code seems rather trivial, so it should be easy to update it or replace it with the official mongodb package. 

I understand that you probably can't  maintain the repository anymore, but it would be cool if you could hand over the respository and the npm namespace or add new colaborators who could help with it! 

fyi: https://github.com/Kikobeats/cacheable-response/ relies on Keyv

**Comment by sittingbool** [comment]
There are many pull requests we just need so. to answer them.

**Comment by B00mGit** [comment]
@macrozone @sittingbool @dandv Hi, did you guys find a solution?

**Comment by macrozone** [comment]
> @macrozone @sittingbool @dandv Hi, did you guys find a solution?

no, still on my desk

**Comment by darovic** [comment]
@B00mGit @macrozone You can set your packages to specifically use one of the pull request commits - #34 or #36.

The relevant excerpt from my `package.json` (as at the time of request #36):
```json
"dependencies": {
    "@keyv/mongo": "github:darovic/keyv-mongo",
```

**Comment by jaredwray** [comment]
Hi @dandv, @macrozone, @darovic, @sittingbool, and @B00mGit sorry for the slow response and we are looking to updating this package monthly now. Sorry for the slow response.
